export const COLORS = {
    // Base toy colors
    TOY_ORANGE: '#FF661F',
    TOY_YELLOW: '#FFE81F',
    TOY_BLUE: '#0066FF',
    TOY_WHITE: '#FFFFFF',
    TOY_BLACK: '#1A1A1A',
    TOY_LIGHT_GRAY: '#ececec',
    TOY_GRAY: '#e0e0e0',
    TOY_DARK_GRAY: '#808080',
};

// Semantic colors (referencing toy colors)
export const SEMANTIC_COLORS = {
    APP_BG: COLORS.TOY_LIGHT_GRAY,
    MODULE_BG: COLORS.TOY_GRAY,
    MODULE_TEXT: COLORS.TOY_BLACK,
    MODULE_FIRED: COLORS.TOY_ORANGE,
    MODULE_SHADOW_PRIMARY: COLORS.TOY_ORANGE,
    MODULE_SHADOW_SECONDARY: COLORS.TOY_BLUE,
    MODULE_SHADOW_TERTIARY: COLORS.TOY_YELLOW,
    STATUS_TEXT: COLORS.TOY_ORANGE,
    OUTPUT_TEXT: COLORS.TOY_DARK_GRAY,
};
